services:
  - type: web
    name: china-trends-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: WALLET_ADDRESS
        value: 0x231a9775e036cfb4abb9c8bd93099ad20a3e288c
      - key: PORT
        value: "3000"
